title: Ruicheng
email: ruichnli@gmail.com
description: >
  Personal website.
github: "https://github.com/Rchli"
selfie: "/img/self.JPG"
# theme: minima

# navigation
# navigation:
#   - title: "About"
#     url: "/"
#   - tiltle: 'News'
#     url: "/news"